-- One native planner response per frozen run revision and verified exploration signal.
CREATE TABLE campaign_replan_model (
    model_id VARCHAR(96) NOT NULL,
    tenant_id VARCHAR(96) NOT NULL,
    subject_name VARCHAR(128) NOT NULL,
    auth_version BIGINT NOT NULL,
    session_id VARCHAR(96) NOT NULL,
    run_id VARCHAR(96) NOT NULL,
    base_revision INT NOT NULL,
    step_id VARCHAR(96) NOT NULL,
    signal_hash CHAR(64) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    model_ref VARCHAR(256) NOT NULL,
    model_version VARCHAR(256) NOT NULL,
    configuration_hash CHAR(64) NOT NULL,
    expires_at BIGINT NOT NULL,
    model_state VARCHAR(16) NOT NULL,
    callback_active BOOLEAN NOT NULL,
    attempt_id VARCHAR(36),
    invocation_json LONGTEXT,
    invocation_hash CHAR(64),
    response_json LONGTEXT,
    response_hash CHAR(64),
    reason_code VARCHAR(96),
    PRIMARY KEY (model_id),
    CONSTRAINT uq_campaign_replan_model_revision UNIQUE (run_id, base_revision),
    CONSTRAINT ck_campaign_replan_model_state CHECK (model_state IN ('PREPARED','DISPATCHING','READY','UNKNOWN','REJECTED','APPLIED')),
    CONSTRAINT ck_campaign_replan_model_callback CHECK (callback_active=FALSE OR model_state IN ('DISPATCHING','READY','UNKNOWN'))
);
