-- Apply only to an explicitly selected EMPTY database. No DROP/TRUNCATE or implicit startup migration.
-- All business tables share ds_0; username/gid shard routing is configured in CommandDataSourceConfiguration.
CREATE TABLE t_account_identity (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 created_at BIGINT NOT NULL,UNIQUE KEY uk_account_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_0 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_0 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_0 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_1 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_1 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_1 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_2 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_2 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_2 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_3 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_3 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_3 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_4 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_4 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_4 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_5 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_5 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_5 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_6 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_6 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_6 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_7 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_7 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_7 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_8 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_8 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_8 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_9 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_9 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_9 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_10 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_10 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_10 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_11 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_11 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_11 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_12 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_12 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_12 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_13 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_13 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_13 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_14 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_14 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_14 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_user_15 (
 id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 password VARCHAR(120) NOT NULL, real_name VARCHAR(100), phone VARCHAR(128), mail VARCHAR(512),
 auth_version BIGINT NOT NULL DEFAULT 1, disabled BOOLEAN NOT NULL DEFAULT FALSE,
 deletion_time BIGINT NOT NULL DEFAULT 0, del_flag INT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_username(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_group_15 (
 id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT NOT NULL, username VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL, name VARCHAR(100) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
 link_count BIGINT NOT NULL DEFAULT 0, job_refs BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 1,
 del_flag INT NOT NULL DEFAULT 0, create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_group(tenant_id,gid), KEY ix_owner(username,del_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_15 (
 id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 full_short_url VARCHAR(300) COLLATE utf8mb4_bin NOT NULL, origin_url VARCHAR(2048) NOT NULL,
 created_type INT NOT NULL DEFAULT 0, valid_date_type INT NOT NULL DEFAULT 0, valid_date DATETIME(3),
 enable_status INT NOT NULL DEFAULT 0, describe_text VARCHAR(1024), favicon VARCHAR(2048), title VARCHAR(512),
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 del_flag INT NOT NULL DEFAULT 0, del_time BIGINT NOT NULL DEFAULT 0,
 create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 KEY ix_group(tenant_id,gid,del_flag,id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_link_route (
 link_id BIGINT NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL, current_gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 domain_norm VARCHAR(253) COLLATE utf8mb4_bin NOT NULL, short_uri CHAR(9) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 origin_url VARCHAR(2048) NOT NULL, route_status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
 expire_at DATETIME(3), route_version BIGINT NOT NULL DEFAULT 1, ownership_version BIGINT NOT NULL DEFAULT 1,
 target_revision BIGINT NOT NULL DEFAULT 1, metadata_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
 created_at BIGINT NOT NULL DEFAULT 0, updated_at BIGINT NOT NULL,
 UNIQUE KEY uk_route_address(domain_norm,short_uri), KEY ix_route_group(tenant_id,current_gid,link_id),
 KEY ix_route_page(tenant_id,current_gid,route_status,created_at,link_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_id_alloc (
 biz_tag VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
 max_id BIGINT NOT NULL, step INT NOT NULL, update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 CHECK(max_id >= 1 AND max_id <= 4503599627370496), CHECK(step > 0)
) ENGINE=InnoDB;
INSERT INTO t_id_alloc(biz_tag,max_id,step) VALUES ('shortlink_global',1,10000);
CREATE TABLE t_cache_generation(cache_name VARCHAR(64) NOT NULL PRIMARY KEY,generation BIGINT NOT NULL) ENGINE=InnoDB;
CREATE TABLE t_id_namespace (
 biz_tag VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
 codec_version VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 key_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL
) ENGINE=InnoDB;
INSERT INTO t_cache_generation VALUES ('redirect-route',1);
CREATE TABLE t_command_result (
 tenant_id BIGINT NOT NULL, command_id VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
 request_digest CHAR(64) NOT NULL, result_json MEDIUMTEXT NOT NULL, created_at BIGINT NOT NULL,
 PRIMARY KEY(tenant_id,command_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_default_group_result(tenant_id BIGINT NOT NULL PRIMARY KEY, command_id VARCHAR(96) NOT NULL,
 gid VARCHAR(64) NOT NULL, created_at BIGINT NOT NULL) ENGINE=InnoDB;
CREATE TABLE t_outbox (
 event_id VARCHAR(64) NOT NULL PRIMARY KEY, topic VARCHAR(128) NOT NULL, event_key VARCHAR(256) NOT NULL,
 payload MEDIUMTEXT NOT NULL, state VARCHAR(16) NOT NULL DEFAULT 'READY',
 attempts INT NOT NULL DEFAULT 0, next_attempt_at BIGINT NOT NULL, lease_until BIGINT NOT NULL DEFAULT 0,
 fence BIGINT NOT NULL DEFAULT 0, created_at BIGINT NOT NULL, published_at BIGINT,
 KEY ix_outbox_due(state,next_attempt_at,lease_until)
) ENGINE=InnoDB;
CREATE TABLE t_account_initialization (
 tenant_id BIGINT NOT NULL PRIMARY KEY, username VARCHAR(64) NOT NULL, command_id VARCHAR(96) NOT NULL UNIQUE,
 state VARCHAR(16) NOT NULL, group_id VARCHAR(64), attempts INT NOT NULL DEFAULT 0, next_attempt_at BIGINT NOT NULL,
 lease_until BIGINT NOT NULL DEFAULT 0, claim_version BIGINT NOT NULL DEFAULT 0,last_error VARCHAR(128),
 created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL, KEY ix_init_due(state,next_attempt_at,lease_until)
) ENGINE=InnoDB;
CREATE TABLE t_session_cleanup_intent(tenant_id BIGINT NOT NULL,auth_version BIGINT NOT NULL,username VARCHAR(64) NOT NULL,
 created_at BIGINT NOT NULL, PRIMARY KEY(tenant_id,auth_version)) ENGINE=InnoDB;
CREATE TABLE t_policy_resource (
 tenant_id BIGINT NOT NULL,link_id BIGINT NOT NULL,policy_revision BIGINT NOT NULL DEFAULT 0,
 next_transition_at BIGINT, PRIMARY KEY(tenant_id,link_id), KEY ix_policy_transition(next_transition_at)
 ,rate_window_seconds INT,rate_window_lock_until BIGINT
) ENGINE=InnoDB;
CREATE TABLE t_risk_policy (
 tenant_id BIGINT NOT NULL,link_id BIGINT NOT NULL,policy_id VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
 action VARCHAR(32) NOT NULL, payload MEDIUMTEXT NOT NULL, effective_from BIGINT NOT NULL,effective_until BIGINT NOT NULL,
 revoked BOOLEAN NOT NULL DEFAULT FALSE,created_at BIGINT NOT NULL,
 PRIMARY KEY(tenant_id,link_id,policy_id),KEY ix_policy_resource(tenant_id,link_id,revoked,effective_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_analytics_epoch (
 singleton_id INT NOT NULL PRIMARY KEY, recovery_epoch VARCHAR(128) NOT NULL, actions_enabled BOOLEAN NOT NULL,gate_fence BIGINT NOT NULL DEFAULT 0,
 updated_at BIGINT NOT NULL, CHECK(singleton_id=1)
) ENGINE=InnoDB;
-- New automatic policy commands remain paused until a verified analytics epoch is explicitly acknowledged.
INSERT INTO t_analytics_epoch(singleton_id,recovery_epoch,actions_enabled,updated_at) VALUES (1,'UNINITIALIZED',FALSE,0);
CREATE TABLE t_analytics_epoch_history(recovery_epoch VARCHAR(128) NOT NULL PRIMARY KEY,gate_fence BIGINT NOT NULL,activated_at BIGINT NOT NULL) ENGINE=InnoDB;
CREATE TABLE t_tenant_quota (
 tenant_id BIGINT NOT NULL PRIMARY KEY, used_rows BIGINT NOT NULL DEFAULT 0,reserved_rows BIGINT NOT NULL DEFAULT 0,
 active_jobs INT NOT NULL DEFAULT 0,validation_jobs INT NOT NULL DEFAULT 0,validation_bytes BIGINT NOT NULL DEFAULT 0,
 CHECK(used_rows>=0 AND reserved_rows>=0 AND active_jobs>=0 AND validation_jobs>=0 AND validation_bytes>=0)
) ENGINE=InnoDB;
CREATE TABLE t_batch_job (
 job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, tenant_id BIGINT NOT NULL,username VARCHAR(64) NOT NULL,auth_version BIGINT NOT NULL,
 request_id VARCHAR(96) COLLATE utf8mb4_bin NOT NULL,request_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,gid VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,
 state VARCHAR(24) NOT NULL,input_kind VARCHAR(8) NOT NULL,input_json MEDIUMTEXT,
 object_bucket VARCHAR(63),object_key VARCHAR(512),object_version VARCHAR(256),declared_sha256 CHAR(64),declared_bytes BIGINT NOT NULL,
 actual_sha256 CHAR(64),actual_bytes BIGINT,parser_version VARCHAR(32) NOT NULL DEFAULT 'creation-ndjson-v1',
 total_rows BIGINT NOT NULL DEFAULT 0,valid_rows BIGINT NOT NULL DEFAULT 0,invalid_rows BIGINT NOT NULL DEFAULT 0,
 succeeded_rows BIGINT NOT NULL DEFAULT 0,failed_rows BIGINT NOT NULL DEFAULT 0,reserved_rows BIGINT NOT NULL DEFAULT 0,
 validation_held BOOLEAN NOT NULL DEFAULT TRUE,references_held BOOLEAN NOT NULL DEFAULT TRUE,
 fence BIGINT NOT NULL DEFAULT 0,lease_owner VARCHAR(64),lease_until BIGINT NOT NULL DEFAULT 0,
 next_attempt_at BIGINT NOT NULL DEFAULT 0,attempts INT NOT NULL DEFAULT 0,last_error VARCHAR(512),created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,
 UNIQUE KEY uk_batch_request(tenant_id,request_id),KEY ix_batch_due(state,next_attempt_at,lease_until,tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE t_batch_row (
 job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,row_no BIGINT NOT NULL,row_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 creation_json TEXT,state VARCHAR(16) NOT NULL,link_id BIGINT,result_json TEXT,error_code VARCHAR(128),
 PRIMARY KEY(job_id,row_no),UNIQUE KEY uk_batch_link(link_id),KEY ix_batch_pending(job_id,state,row_no)
) ENGINE=InnoDB;
CREATE TABLE t_metadata_job (
 job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,tenant_id BIGINT NOT NULL,link_id BIGINT NOT NULL,target_revision BIGINT NOT NULL,
 url_digest CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,origin_url VARCHAR(2048) NOT NULL,state VARCHAR(16) NOT NULL DEFAULT 'READY',
 attempts INT NOT NULL DEFAULT 0,fence BIGINT NOT NULL DEFAULT 0,lease_owner VARCHAR(64),lease_until BIGINT NOT NULL DEFAULT 0,
 next_attempt_at BIGINT NOT NULL DEFAULT 0,last_error VARCHAR(512),created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,
 UNIQUE KEY uk_metadata_revision(tenant_id,link_id,target_revision,url_digest),KEY ix_metadata_due(state,next_attempt_at,lease_until)
) ENGINE=InnoDB;
