-- Official ClickHouse Kafka Connect landing schemas match Java record JSON exactly.
CREATE TABLE IF NOT EXISTS shortlink_analytics.derived_events (
 kind LowCardinality(String),
 clusterId String,
 topicId String,
 sourceTopic String,
 sourcePartition UInt32,
 sourceOffset UInt64,
 receivedAt Int64,
 timestampType String,
 eventId String,
 payloadHash FixedString(64),
 tenantId String,
 linkId UInt64,
 occurredAt Int64,
 visitorHash String,
 ipHash String,
 browser String,
 os String,
 device String,
 country String,
 refererDomain String,
 requestSource String,
 decisionStage String,
 status UInt16,
 reason String,
 validationVersion String,
 validationResult String,
 detailDatasetVersion String,
 parserVersion String,
 hashVersion String
) ENGINE=MergeTree ORDER BY (sourceTopic,sourcePartition,sourceOffset,clusterId,topicId)
TTL toDateTime(greatest(receivedAt,0)/1000)+INTERVAL 180 DAY;
CREATE MATERIALIZED VIEW IF NOT EXISTS shortlink_analytics.derived_events_mv TO shortlink_analytics.event_receipts AS
SELECT kind AS kind,
clusterId AS cluster_id,
topicId AS topic_id,
sourceTopic AS source_topic,
sourcePartition AS source_partition,
sourceOffset AS source_offset,
receivedAt AS received_at,
timestampType AS timestamp_type,
eventId AS event_id,
payloadHash AS payload_hash,
tenantId AS tenant_id,
linkId AS link_id,
occurredAt AS occurred_at,
visitorHash AS visitor_hash,
ipHash AS ip_hash,
browser AS browser,
os AS os,
device AS device,
country AS country,
refererDomain AS referer_domain,
requestSource AS request_source,
decisionStage AS decision_stage,
status AS status,
reason AS reason,
validationVersion AS validation_version,
validationResult AS validation_result,
detailDatasetVersion AS dataset_version,
parserVersion AS parser_version,
hashVersion AS hash_version FROM shortlink_analytics.derived_events;
CREATE TABLE IF NOT EXISTS shortlink_analytics.derived_windows (
 tenantId String,
 linkId UInt64,
 windowStart Int64,
 windowEnd Int64,
 bucket Int32,
 revision UInt64,
 pv UInt64,
 uv Float64,
 uip Float64,
 visitorSketch String,
 ipSketch String,
 buildId String,
 recoveryEpoch String,
 metricVersion String,
 detailDatasetVersion String
) ENGINE=MergeTree ORDER BY (buildId,windowStart,tenantId,linkId,revision);
CREATE MATERIALIZED VIEW IF NOT EXISTS shortlink_analytics.derived_windows_mv TO shortlink_analytics.window_results AS
SELECT tenantId AS tenant_id,
linkId AS link_id,
windowStart AS window_start,
windowEnd AS window_end,
revision AS revision,
pv AS pv,
uv AS uv,
uip AS uip,
visitorSketch AS visitor_sketch,
ipSketch AS ip_sketch,
buildId AS build_id,
recoveryEpoch AS recovery_epoch,
metricVersion AS metric_version,
detailDatasetVersion AS dataset_version FROM shortlink_analytics.derived_windows WHERE bucket=-1;
