CREATE TABLE IF NOT EXISTS t_agent_graph_checkpoint (
    id BIGINT NOT NULL AUTO_INCREMENT,
    thread_id VARCHAR(128) NOT NULL,
    trace_id VARCHAR(128) NOT NULL,
    graph_name VARCHAR(128) NOT NULL,
    graph_version VARCHAR(64) NOT NULL,
    checkpoint_json LONGTEXT NOT NULL,
    checkpoint_version BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_graph_checkpoint UNIQUE (thread_id, graph_name, graph_version)
);

CREATE TABLE IF NOT EXISTS t_agent_schema_migration_history (
    version VARCHAR(64) NOT NULL,
    description VARCHAR(256) NOT NULL,
    script_name VARCHAR(256) NOT NULL,
    applied_by VARCHAR(256) NOT NULL,
    applied_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (version)
);

CREATE TABLE IF NOT EXISTS t_agent_pending_action (
    id BIGINT NOT NULL AUTO_INCREMENT,
    action_id VARCHAR(128) NOT NULL,
    agent_type VARCHAR(64) NOT NULL,
    action_type VARCHAR(128) NOT NULL,
    payload_version INTEGER NOT NULL,
    authorization_scope VARCHAR(32) NOT NULL,
    owner_username VARCHAR(128) NOT NULL DEFAULT '',
    gid VARCHAR(64) NOT NULL DEFAULT '',
    target_type VARCHAR(32) NOT NULL,
    target_key VARCHAR(512) NOT NULL,
    target_ref_json LONGTEXT NOT NULL,
    title VARCHAR(256) NOT NULL,
    summary VARCHAR(2048) NOT NULL DEFAULT '',
    payload_json LONGTEXT NOT NULL,
    payload_hash VARCHAR(128) NOT NULL,
    evidence_json LONGTEXT NOT NULL,
    idempotency_key VARCHAR(512) NOT NULL,
    active_slot_key CHAR(64) NULL,
    status VARCHAR(32) NOT NULL,
    expire_time TIMESTAMP NULL,
    version BIGINT NOT NULL DEFAULT 0,
    execution_token VARCHAR(128) NOT NULL DEFAULT '',
    execution_lease_until TIMESTAMP NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    result_json LONGTEXT NOT NULL,
    failure_code VARCHAR(128) NOT NULL DEFAULT '',
    failure_message VARCHAR(2048) NOT NULL DEFAULT '',
    proposed_by VARCHAR(128) NOT NULL,
    confirmed_by VARCHAR(128) NOT NULL DEFAULT '',
    confirmed_time TIMESTAMP NULL,
    rejected_by VARCHAR(128) NOT NULL DEFAULT '',
    rejected_time TIMESTAMP NULL,
    rejection_reason VARCHAR(2048) NOT NULL DEFAULT '',
    rejection_review_action VARCHAR(32) NULL,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    event_id VARCHAR(128) NOT NULL DEFAULT '',
    batch_id VARCHAR(128) NOT NULL DEFAULT '',
    session_id VARCHAR(256) NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_pending_action_action_id UNIQUE (action_id),
    CONSTRAINT uk_agent_pending_action_type_idempotency UNIQUE (action_type, idempotency_key),
    CONSTRAINT uk_agent_pending_action_active_slot UNIQUE (active_slot_key),
    KEY idx_agent_pending_action_gid_status (gid, status, update_time),
    KEY idx_agent_pending_action_execution_lease (status, execution_lease_until),
    KEY idx_agent_pending_action_event_id (event_id),
    KEY idx_agent_pending_action_batch_gid (batch_id, gid)
);

CREATE TABLE IF NOT EXISTS t_agent_risk_profile_batch (
    id BIGINT NOT NULL AUTO_INCREMENT,
    batch_id VARCHAR(128) NOT NULL,
    window_start TIMESTAMP NOT NULL,
    window_end TIMESTAMP NOT NULL,
    status VARCHAR(32) NOT NULL,
    owner_token VARCHAR(128) NOT NULL DEFAULT '',
    lease_until TIMESTAMP,
    scanned_count INTEGER NOT NULL DEFAULT 0,
    generated_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    analysis_job_count INTEGER NOT NULL DEFAULT 0,
    failures_json LONGTEXT NOT NULL,
    error_summary VARCHAR(2048) NOT NULL DEFAULT '',
    start_time TIMESTAMP,
    finish_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_risk_profile_batch_id UNIQUE (batch_id),
    KEY idx_agent_risk_profile_batch_window (window_end, status),
    KEY idx_agent_risk_profile_batch_lease (status, lease_until),
    KEY idx_agent_risk_profile_batch_recovery (update_time, window_end, id, status, lease_until)
);

CREATE TABLE IF NOT EXISTS t_agent_risk_analysis_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    job_id VARCHAR(128) NOT NULL,
    batch_id VARCHAR(128) NOT NULL,
    gid VARCHAR(64) NOT NULL,
    graph_name VARCHAR(128) NOT NULL,
    graph_version VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_time TIMESTAMP,
    owner_token VARCHAR(128) NOT NULL DEFAULT '',
    lease_until TIMESTAMP,
    session_id VARCHAR(256) NOT NULL,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    error_summary VARCHAR(2048) NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_risk_analysis_job_id UNIQUE (job_id),
    CONSTRAINT uk_agent_risk_analysis_job_scope UNIQUE (batch_id, gid, graph_name, graph_version),
    KEY idx_agent_risk_analysis_job_claim (status, next_retry_time, lease_until)
);

CREATE TABLE IF NOT EXISTS t_agent_risk_event (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_id VARCHAR(128) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    gid VARCHAR(64) NOT NULL DEFAULT '',
    domain VARCHAR(256) NOT NULL DEFAULT '',
    short_uri VARCHAR(128) NOT NULL DEFAULT '',
    full_short_url VARCHAR(512) NOT NULL DEFAULT '',
    risk_score INTEGER NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    reason_codes_json LONGTEXT NOT NULL,
    evidence_json LONGTEXT NOT NULL,
    recommended_actions_json LONGTEXT NOT NULL,
    agent_summary VARCHAR(2048) NOT NULL DEFAULT '',
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    session_id VARCHAR(128) NOT NULL DEFAULT '',
    source VARCHAR(64) NOT NULL,
    event_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_risk_event_event_id UNIQUE (event_id),
    KEY idx_agent_risk_event_gid_time (gid, event_time),
    KEY idx_agent_risk_event_target_time (target_type, domain, short_uri, event_time)
);

CREATE TABLE IF NOT EXISTS t_agent_risk_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT,
    target_type VARCHAR(32) NOT NULL,
    gid VARCHAR(64) NOT NULL DEFAULT '',
    domain VARCHAR(256) NOT NULL DEFAULT '',
    short_uri VARCHAR(128) NOT NULL DEFAULT '',
    full_short_url VARCHAR(512) NOT NULL DEFAULT '',
    risk_score INTEGER NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    reason_codes_json LONGTEXT NOT NULL,
    risk_cards_json LONGTEXT NOT NULL,
    watch_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    policy_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    last_event_id VARCHAR(128) NOT NULL DEFAULT '',
    last_trace_id VARCHAR(128) NOT NULL DEFAULT '',
    last_scan_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_risk_snapshot_target UNIQUE (target_type, gid, domain, short_uri),
    KEY idx_agent_risk_snapshot_gid_score (gid, risk_score)
);

CREATE TABLE IF NOT EXISTS t_agent_short_link_risk_profile (
    id BIGINT NOT NULL AUTO_INCREMENT,
    batch_id VARCHAR(128) NOT NULL,
    gid VARCHAR(64) NOT NULL,
    domain VARCHAR(256) NOT NULL,
    short_uri VARCHAR(128) NOT NULL,
    full_short_url VARCHAR(512) NOT NULL,
    profile_window_start TIMESTAMP NOT NULL,
    profile_window_end TIMESTAMP NOT NULL,
    pv_2h INTEGER NOT NULL DEFAULT 0,
    uv_2h INTEGER NOT NULL DEFAULT 0,
    pv_24h INTEGER NOT NULL DEFAULT 0,
    uv_24h INTEGER NOT NULL DEFAULT 0,
    pv_7d INTEGER NOT NULL DEFAULT 0,
    uv_7d INTEGER NOT NULL DEFAULT 0,
    pv_growth_2h_vs_24h_avg DECIMAL(12,4),
    top_ip_share DECIMAL(12,4),
    top_visitor_share DECIMAL(12,4),
    top_region_share DECIMAL(12,4),
    top_device_share DECIMAL(12,4),
    top_browser_share DECIMAL(12,4),
    pv_per_uv DECIMAL(12,4),
    peak_hour_share DECIMAL(12,4),
    repeat_visit_ratio DECIMAL(12,4),
    anomaly_score INTEGER NOT NULL DEFAULT 0,
    risk_score INTEGER NOT NULL DEFAULT 0,
    risk_level VARCHAR(32) NOT NULL,
    reason_codes_json LONGTEXT NOT NULL,
    profile_json LONGTEXT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_short_link_profile_batch_target UNIQUE (batch_id, gid, domain, short_uri),
    KEY idx_agent_short_link_profile_gid_time (gid, profile_window_end),
    KEY idx_agent_short_link_profile_target_time (domain, short_uri, profile_window_end),
    KEY idx_agent_short_link_profile_gid_score (gid, risk_score)
);

CREATE TABLE IF NOT EXISTS t_agent_group_risk_profile (
    id BIGINT NOT NULL AUTO_INCREMENT,
    batch_id VARCHAR(128) NOT NULL,
    gid VARCHAR(64) NOT NULL,
    profile_window_start TIMESTAMP NOT NULL,
    profile_window_end TIMESTAMP NOT NULL,
    total_short_links_scanned INTEGER NOT NULL DEFAULT 0,
    low_risk_count INTEGER NOT NULL DEFAULT 0,
    medium_risk_count INTEGER NOT NULL DEFAULT 0,
    high_risk_count INTEGER NOT NULL DEFAULT 0,
    watching_count INTEGER NOT NULL DEFAULT 0,
    disabled_count INTEGER NOT NULL DEFAULT 0,
    avg_risk_score DECIMAL(12,4) NOT NULL DEFAULT 0,
    max_risk_score INTEGER NOT NULL DEFAULT 0,
    group_risk_score INTEGER NOT NULL DEFAULT 0,
    group_risk_level VARCHAR(32) NOT NULL,
    group_reason_codes_json LONGTEXT NOT NULL,
    top_risk_short_links_json LONGTEXT NOT NULL,
    risk_trend_7d_json LONGTEXT NOT NULL,
    agent_summary VARCHAR(2048) NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_group_profile_batch_gid UNIQUE (batch_id, gid),
    KEY idx_agent_group_profile_gid_time (gid, profile_window_end),
    KEY idx_agent_group_profile_gid_score (gid, group_risk_score)
);

CREATE TABLE IF NOT EXISTS t_agent_risk_review (
    id BIGINT NOT NULL AUTO_INCREMENT,
    review_id VARCHAR(128) NOT NULL,
    event_id VARCHAR(128) NOT NULL DEFAULT '',
    target_type VARCHAR(32) NOT NULL,
    gid VARCHAR(64) NOT NULL DEFAULT '',
    domain VARCHAR(256) NOT NULL DEFAULT '',
    short_uri VARCHAR(128) NOT NULL DEFAULT '',
    full_short_url VARCHAR(512) NOT NULL DEFAULT '',
    review_action VARCHAR(64) NOT NULL,
    reviewer VARCHAR(128) NOT NULL,
    review_note VARCHAR(2048) NOT NULL DEFAULT '',
    review_time TIMESTAMP NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_risk_review_review_id UNIQUE (review_id),
    KEY idx_agent_risk_review_event_id (event_id),
    KEY idx_agent_risk_review_gid_time (gid, review_time)
);

CREATE TABLE IF NOT EXISTS t_agent_risk_policy (
    id BIGINT NOT NULL AUTO_INCREMENT,
    policy_id VARCHAR(128) NOT NULL,
    policy_key VARCHAR(512) NOT NULL,
    idempotency_key VARCHAR(512) NULL,
    policy_version BIGINT NULL,
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    gid VARCHAR(64) NOT NULL DEFAULT '',
    domain VARCHAR(256) NOT NULL DEFAULT '',
    short_uri VARCHAR(128) NOT NULL DEFAULT '',
    ip_hash VARCHAR(128) NOT NULL DEFAULT '',
    policy_payload_json LONGTEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    effective_time TIMESTAMP NOT NULL,
    expire_time TIMESTAMP,
    source VARCHAR(64) NOT NULL,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    event_id VARCHAR(128) NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_risk_policy_policy_id UNIQUE (policy_id),
    KEY idx_agent_risk_policy_key_status (policy_key, status),
    KEY idx_agent_risk_policy_key_version (policy_key, policy_version),
    KEY idx_agent_risk_policy_gid_status (gid, status)
);

CREATE TABLE IF NOT EXISTS t_agent_risk_policy_effective (
    id BIGINT NOT NULL AUTO_INCREMENT,
    policy_key VARCHAR(512) NOT NULL,
    policy_id VARCHAR(128) NOT NULL,
    policy_version BIGINT NOT NULL,
    gid VARCHAR(64) NOT NULL DEFAULT '',
    action VARCHAR(64) NOT NULL,
    desired_state VARCHAR(32) NOT NULL,
    policy_payload_json LONGTEXT NOT NULL,
    redis_value_json LONGTEXT NOT NULL,
    effective_time TIMESTAMP NOT NULL,
    expire_time TIMESTAMP NULL,
    sync_status VARCHAR(32) NOT NULL,
    last_outbox_id VARCHAR(128) NOT NULL DEFAULT '',
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_risk_policy_effective_key UNIQUE (policy_key)
);

CREATE TABLE IF NOT EXISTS t_agent_risk_policy_sync_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT,
    outbox_id VARCHAR(128) NOT NULL,
    policy_key VARCHAR(512) NOT NULL,
    policy_id VARCHAR(128) NOT NULL,
    policy_version BIGINT NOT NULL,
    operation VARCHAR(32) NOT NULL,
    redis_value_json LONGTEXT NOT NULL,
    expected_redis_value LONGTEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_time TIMESTAMP NULL,
    owner_token VARCHAR(128) NOT NULL DEFAULT '',
    lease_until TIMESTAMP NULL,
    last_error VARCHAR(2048) NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_risk_policy_sync_outbox_id UNIQUE (outbox_id),
    CONSTRAINT uk_agent_risk_policy_sync_outbox_operation UNIQUE (policy_key, policy_version, operation),
    KEY idx_agent_risk_policy_sync_outbox_claim (status, next_retry_time, lease_until),
    KEY idx_agent_risk_policy_sync_outbox_key_version (policy_key, policy_version)
);

CREATE TABLE IF NOT EXISTS t_agent_risk_action_audit (
    id BIGINT NOT NULL AUTO_INCREMENT,
    audit_id VARCHAR(128) NOT NULL,
    policy_id VARCHAR(128) NOT NULL DEFAULT '',
    event_id VARCHAR(128) NOT NULL DEFAULT '',
    action VARCHAR(64) NOT NULL,
    executor_type VARCHAR(64) NOT NULL,
    executor VARCHAR(128) NOT NULL,
    reason VARCHAR(2048) NOT NULL DEFAULT '',
    evidence_json LONGTEXT NOT NULL,
    trace_id VARCHAR(128) NOT NULL DEFAULT '',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_agent_risk_action_audit_audit_id UNIQUE (audit_id),
    KEY idx_agent_risk_action_audit_policy_id (policy_id),
    KEY idx_agent_risk_action_audit_event_id (event_id)
);
